import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

/**
 * Flat config, using eslint-config-next's native flat exports.
 *
 * The Next scaffold ships a config that wraps the old .eslintrc format in
 * @eslint/eslintrc's FlatCompat shim. Under eslint-config-next 16 that shim
 * throws ("Converting circular structure to JSON") because the plugin objects
 * it tries to serialise now contain circular references. The flat exports need
 * no shim, so @eslint/eslintrc is no longer a dependency.
 */
const eslintConfig = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      "next-env.d.ts",
      // Generated by the shadcn CLI. We own these files once they land, but
      // linting someone else's generated variants produces noise, not signal.
      "src/components/ui/**",
    ],
  },
  ...coreWebVitals,
  ...typescript,
];

export default eslintConfig;
